// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using wedding_planner.Models;

namespace wedding_planner.Migrations
{
    [DbContext(typeof(WeddingContext))]
    [Migration("20180416195059_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("wedding_planner.Models.Guest", b =>
                {
                    b.Property<int>("guestid")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("created_at");

                    b.Property<DateTime>("updated_at");

                    b.Property<int>("userid");

                    b.Property<int>("weddingid");

                    b.HasKey("guestid");

                    b.HasIndex("userid");

                    b.HasIndex("weddingid");

                    b.ToTable("guests");
                });

            modelBuilder.Entity("wedding_planner.Models.User", b =>
                {
                    b.Property<int>("userid")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("created_at");

                    b.Property<string>("email");

                    b.Property<string>("first_name");

                    b.Property<string>("last_name");

                    b.Property<string>("password");

                    b.Property<DateTime>("updated_at");

                    b.HasKey("userid");

                    b.ToTable("users");
                });

            modelBuilder.Entity("wedding_planner.Models.Wedding", b =>
                {
                    b.Property<int>("weddingid")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("address");

                    b.Property<DateTime>("created_at");

                    b.Property<DateTime>("date");

                    b.Property<DateTime>("updated_at");

                    b.Property<int>("userid");

                    b.Property<string>("wedder_one");

                    b.Property<string>("wedder_two");

                    b.HasKey("weddingid");

                    b.HasIndex("userid");

                    b.ToTable("weddings");
                });

            modelBuilder.Entity("wedding_planner.Models.Guest", b =>
                {
                    b.HasOne("wedding_planner.Models.User", "user")
                        .WithMany("visitants")
                        .HasForeignKey("userid")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("wedding_planner.Models.Wedding", "wedding")
                        .WithMany("guests")
                        .HasForeignKey("weddingid")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("wedding_planner.Models.Wedding", b =>
                {
                    b.HasOne("wedding_planner.Models.User", "user")
                        .WithMany("weddings")
                        .HasForeignKey("userid")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
